swagger: "2.0"
info:
  description: "Swagger doc for connections app"
  version: "1.0.0"
  title: "Connections"
schemes:
- "https"
- "http"
paths:
  /people:
    get:
      summary: "Get list of people"
      description: ""
      operationId: "getPeople"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Person"
        400:
          description: "Invalid input"
    post:
      summary: "Create a new person"
      description: ""
      operationId: "createPerson"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Person object that needs to be created"
        required: true
        schema:
          $ref: "#/definitions/Person"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/Person"
        400:
          description: "Invalid input"
  /people/{person_id}/degrees_of_separation?degrees={max_degrees}:
    get:
      summary: "Get a list of people separated by a maximum number of people"
      description: ""
      operationId: "getPeopleByDegreesOfSeparation"
      produces:
      - :application/json"
      parameters:
      - in: path
        name: person_id
        required: true
        schema:
          type: integer
          minimum: 1
        description: Numeric ID of the person to find the connected people
      - in: path
        name: max_degrees
        required: true
        schema:
          type: integer
          minimum: 1
          maximum: 6
        description: Integer value of the limit of the degrees which people can from separated
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PersonByDegreesOfSeparation"
        400:
          description: "Invalid input"
  /connections:
    get:
      summary: "Get list of connections"
      description: ""
      operationId: "getConnections"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Connection"
        400:
          description: "Invalid input"
    post:
      summary: "Create a new connection"
      description: ""
      operationId: "createConnection"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Connection object that needs to be created"
        required: true
        schema:
          $ref: "#/definitions/Connection"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/Connection"
        400:
          description: "Invalid input"
  /connections:
    get:
      summary: "Get list of connections"
      description: ""
      operationId: "getConnections"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Connection"
        400:
          description: "Invalid input"
    post:
      summary: "Create a new connection"
      description: ""
      operationId: "createConnection"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Connection object that needs to be created"
        required: true
        schema:
          $ref: "#/definitions/Connection"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/Connection"
        400:
          description: "Invalid input"
  /connections/{connection_id}:
    patch:
      summary: "Update the connection tpye for a given connection"
      parameters:
        - name: connection_id
        in: path
        required: true
        description: Numeric ID of the connection to modify
        schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                connection_type:
                  type: string
      description: ""
      operationId: "updateConnection"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Connection"
        400:
          description: "Invalid connection_type"
        404:
          description: "Invalid connection_id"
definitions:
  Person:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      first_name:
        type: "string"
      last_name:
        type: "string"
      email:
        type: "string"

  Connection:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      from_person_id:
        type: "integer"
        format: "int64"
        description: "From Person"
      to_person_id:
        type: "integer"
        format: "int64"
        description: "To Person"
      connection_type:
        type: "string"
        description: "Connection Type"
        enum:
        - "mother"
        - "father"
        - "son"
        - "daughter"
        - "husband"
        - "wife"
        - "brother"
        - "sister"
        - "friend"
        - "coworker"

  PersonByDegreesOfSeparation:
    type: "object"
    properties:
      separation_degrees:
        type: "integer"
        format: "int64"
      id:
        type: "integer"
        format: "int64"
      first_name:
        type: "string"
      last_name:
        type: "string"
      email:
        type: "string"


externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
